version: '3'
services:
    mongodb-dev:
        container_name: bot-mongodb-dev
        image: 'bitnami/mongodb:latest'
        volumes:
            - mongodb:/bitnami/mongodb
        environment:
            - MONGODB_ROOT_PASSWORD=bot
            - MONGODB_ROOT_USER=bot
            - MONGODB_DATABASE=bot
        ports:
            - "50030:27017"

volumes:
    mongodb:
        driver: local
