FROM node:latest

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN yarn set version berry

# Install dependencies
COPY package.json /usr/src/app/
RUN yarn install

# Bundle app source
COPY src/ /usr/src/app/src

CMD [ "yarn", "run", "dev" ]
