name: Automation
on: push
jobs:
  prettier:
    name: Prettier Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set yarn version
      run: yarn set version berry
    - name: Install modules
      run: yarn install
    - name: Run ESLint
      run: yarn run prettier-format
  security:
    name: Snyk Security Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set yarn version
        run: yarn set version berry
      - name: Install modules
        run: yarn install
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test --all-projects
  lint:
    name: Eslint linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set yarn version
      run: yarn set version berry
    - name: Install modules
      run: yarn install
    - name: Run ESLint
      run: yarn run lint
